### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=JetBrains Rider

###

@BankApi_HostAddress = http://localhost:5015

GET {{BankApi_HostAddress}}/accounts

###

POST http://localhost:5015/accounts
Content-Type: application/json

{
  "holder": "Teste",
  "accountType": 0
}

###

POST http://localhost:5015/accounts/deposit
Content-Type: application/json

{
  "accountId": 1,
  "amount": 200
}

###

POST http://localhost:5015/accounts/withdraw
Content-Type: application/json

{
  "accountId": 1,
  "amount": 50
}

###

POST http://localhost:5015/customers
Content-Type: application/json

{
  "fullName": "Pedro",
  "email": "teste@gmail.com",
  "document": "
}

###